.TH TODO 1 "21 January 2020" "v2020.01.21"

.SH NAME
todo \- a minimalist todo list manager

.SH SYNOPSIS
.B todo
[-vhex] [-a "todo item"] [-d todo-number] [-d "todo phrase"]
.P

.SH DESRIPTION
.B todo
is a simple, minimalist todo list manager. Users can
add items to a todo list or delete them. Deleted items
are archived and can be reviewed.
.PP
The default location of the todo list can be set with
the
.B TODO
environment variable. If unset, a the default file is
.B ~/todo.txt.
.PP
If
.B todo
is used within a tmux session, the filename of the todo
list inherits the name of the current session. This
allows for unique todo lists based on tmux context.
.PP
The options are as follows:

.TP
.B "no parameters"
If no parameters are passed to 
.B todo,
then the current todo list will be displayed to standard out.
.TP
.B -a " quoted_todo_item"
Add a new todo list item
.TP
.B -d " item_number_or_phrase"
Delete a todo list item by its number or by a string.
If a string is provided, any todo list item that matches
that string will be removed. Deleted items are moved
to the archive.
.PP
The archive file is named identically to the todo file
with the exception of a
.B .archive
added before the extension. For example, todo.txt would
have an archive named todo.archive.txt in the same folder.
.TP
.B -e
Open the todo file in your editor.
.TP
.B -x
Display the archive file.
.TP
.B -v
Display current version information.
.TP 
.B -h
Show the help.

.SH EXIT STATUS
The
.B todo
utility exits 0 on success, and >0 if an error occurs.

.SH EXAMPLES
.TP
.B todo
Displays the current todo list
.TP
.B todo -a `this is a new todo list item'
Adds a new item to the current todo list
.TP
.B todo -d 3
Deletes item #3 from the current todo list
.TP
.B todo -x
Shows the archive for the current todo list

.SH BUGS
Report issues at the git repository at
.B https://github.com/jamestomasino/todo

.SH AUTHOR
James Tomasino <james (at) tomasino (dot) org>
